#! /usr/bin/env node
var connect = require('connect')
  , http = require('http');

var app = connect()
  .use(connect.static('.'))
  .use(connect.directory('.'))
;

http.createServer(app).listen(5331);
